monthlyIncome = input("Enter your monthly income: ")
monthlyExpenses = input("Enter your total monthly expenses: ")
monthlySavings = float(monthlyIncome) - float(monthlyExpenses)
projectedSavings = float(monthlySavings) * 2 + (float(monthlySavings) * 12 * 0.05)
print("Your monthly savings are ",monthlySavings,)
print("Projected savings after one year, with interest, is: ",projectedSavings,)
